services:
  loreglyph:
    build:
      context: ./LoreGlyph/
      dockerfile: Dockerfile
    ports:
      - "5248:8080"
      - "8081:8081"

  frontend:
    build:
      context: ./LoreGlyph/Frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"